// Code generated by go generate DO NOT EDIT.
// If you edit this file, write "// DO NOT OVERWRITE" on the first line.

package controllers

import usecases "github.com/rinoguchi/microblog/usecases/models"

func (comment Comment) ToUComment() usecases.UComment {
	return usecases.UComment{
		CreatedAt: comment.CreatedAt,
		Id:        comment.Id,
		Text:      comment.Text,
		UpdatedAt: comment.UpdatedAt,
	}
}

func FromUComment(uComment usecases.UComment) Comment {
	return Comment{
		CreatedAt: uComment.CreatedAt,
		Id:        uComment.Id,
		Text:      uComment.Text,
		UpdatedAt: uComment.UpdatedAt,
	}
}
