// Code generated by go generate DO NOT EDIT.
// If you edit this file, write "// DO NOT OVERWRITE" on the first line.

package usecases

import (
	"time"

	"github.com/rinoguchi/microblog/entities"
)

type UComment struct {
	CreatedAt *time.Time
	Id        *int64
	Text      string
	UpdatedAt *time.Time
}

func (uComment UComment) ToCommentEntity() entities.CommentEntity {
	return entities.CommentEntity{
		CreatedAt: uComment.CreatedAt,
		Id:        uComment.Id,
		Text:      uComment.Text,
		UpdatedAt: uComment.UpdatedAt,
	}
}

func FromCommentEntity(comment entities.CommentEntity) UComment {
	return UComment{
		CreatedAt: comment.CreatedAt,
		Id:        comment.Id,
		Text:      comment.Text,
		UpdatedAt: comment.UpdatedAt,
	}
}
