// Code generated by go generate DO NOT EDIT.
// If you edit this file, write "// DO NOT OVERWRITE" on the first line.

package usecases

import (
	"github.com/rinoguchi/microblog/entities"
)

type UGetCommentsParams struct {
	Query     *string
	Year      *string
	Yearmonth *string
}

func (uGetCommentsParams UGetCommentsParams) ToGetCommentsParamsEntity() entities.GetCommentsParamsEntity {
	return entities.GetCommentsParamsEntity{
		Query:     uGetCommentsParams.Query,
		Year:      uGetCommentsParams.Year,
		Yearmonth: uGetCommentsParams.Yearmonth,
	}
}

func FromGetCommentsParamsEntity(getCommentsParams entities.GetCommentsParamsEntity) UGetCommentsParams {
	return UGetCommentsParams{
		Query:     getCommentsParams.Query,
		Year:      getCommentsParams.Year,
		Yearmonth: getCommentsParams.Yearmonth,
	}
}
