// Code generated by go generate DO NOT EDIT.
// If you edit this file, write "// DO NOT OVERWRITE" on the first line.

package repositories

import "github.com/rinoguchi/microblog/entities"

func (dbComment DbComment) ToCommentEntity() entities.CommentEntity {
	return entities.CommentEntity{
		Id:        dbComment.Id,
		Text:      dbComment.Text,
		CreatedAt: dbComment.CreatedAt,
		UpdatedAt: dbComment.UpdatedAt,
	}
}

func FromCommentEntity(comment entities.CommentEntity) DbComment {
	return DbComment{
		Id:        comment.Id,
		Text:      comment.Text,
		CreatedAt: comment.CreatedAt,
		UpdatedAt: comment.UpdatedAt,
	}
}
